# Generated by Django 5.0.4 on 2024-06-05 06:07

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.UUIDField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.FloatField()),
                ('item_description', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='menu_images/')),
                ('item_category', models.CharField(max_length=30)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='New_user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_phone', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('restaurent_id', models.UUIDField(primary_key=True, serialize=False)),
                ('restaurent_name', models.CharField(max_length=30)),
                ('restaurent_description', models.TextField()),
                ('restaurent_address', models.CharField(max_length=100)),
                ('restaurent_phone', models.CharField(max_length=100)),
                ('restaurent_image', models.ImageField(upload_to='restaurent_images/')),
                ('restaurent_rating', models.FloatField()),
                ('restaurent_delivery_charge', models.FloatField()),
                ('restaurent_cuisine', models.CharField(max_length=50)),
                ('is_open', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('delivery_address', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='tomato.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.new_user')),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.restaurent')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.restaurent'),
        ),
    ]
