# Generated by Django 5.0.4 on 2024-06-12 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.FloatField()),
                ('item_image', models.ImageField(upload_to='menu_images/')),
                ('item_category', models.CharField(max_length=30)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomato.menu')),
            ],
        ),
    ]
