# Generated by Django 5.0.4 on 2024-06-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomato', '0004_addtocart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addtocart',
        ),
    ]
